version: '3.9'
services:
  database:
    container_name: greengame
    image: mariadb:11.0.2
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      # - ./data:/var/lib/mysql
      - ./config/mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  nginx:
    container_name: nginx
    image: nginx:1.25.3
    restart: unless-stopped
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./games:/usr/share/nginx/html/levels
    ports:
      - "80:80"